"""book

Revision ID: 877deee6e287
Revises: cd7f7382cb23
Create Date: 2020-04-16 01:39:27.761088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '877deee6e287'
down_revision = 'cd7f7382cb23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('title', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'title')
    # ### end Alembic commands ###
