"""book

Revision ID: d91ec4b6fdb0
Revises: c55ef8bf0f76
Create Date: 2020-04-20 11:17:42.000156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91ec4b6fdb0'
down_revision = 'c55ef8bf0f76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'book', 'book_type', ['book_type'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    # ### end Alembic commands ###
